version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mon_app"
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
